import Head from 'next/head'
import Image from 'next/image'
import Box from '../components/box'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to Auto Time-Table Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Time-Table Bot
        </h1>
        <Box />
      </main>

      <footer className={styles.footer}>
        <a
          href="http://github.com/timbaron"
          target="_blank"
          rel="noopener noreferrer"
        >
          Proudly created with Love by Akiode Timothy
          
        </a>
      </footer>
    </div>
  )
}
